snap_bone_fixed_name_list = [
            ['Hips', 'Hip'],
            ['Spine', 'Spine_0'],
            ['Upper Chest', 'Spine_1'],
            ['Chest', 'Spine_2'],
            ['Neck', 'Neck_0'],
            ['Neck', 'Neck_0_HJ_00'],

            ['Head.001', 'Head'],

            ['Left shoulder', 'L_Shoulder'],
            ['Left arm', 'L_UpperArm'],
            ['Left elbow', 'L_Forearm'],
            ['Left wrist', 'L_Hand'],
            ['Left wrist', 'L_Wep'],

            ['Thumb0_L', 'L_Thumb1'],
            ['Thumb1_L', 'L_Thumb2'],
            ['Thumb2_L', 'L_Thumb3'],

            ['Thumb0_L', 'L_Thumb_HJ_00'],
            ['Thumb1_L', 'L_Thumb_HJ_01'],
            ['Thumb2_L', 'L_Thumb_HJ_02'],
            ['Thumb0_L', 'L_Thumb_HJ_03'],

            ['IndexFinger1_L', 'L_IndexF1'],
            ['IndexFinger2_L', 'L_IndexF2'],
            ['IndexFinger3_L', 'L_IndexF3'],

            ['IndexFinger1_L', 'L_IndexF_HJ_01'],
            ['IndexFinger2_L', 'L_IndexF_HJ_02'],
            ['IndexFinger3_L', 'L_IndexF_HJ_03'],
            ['IndexFinger1_L', 'L_IndexF_HJ_00'],
            ['IndexFinger1_L', 'L_IndexF_HJ_04'],

            ['MiddleFinger1_L', 'L_MiddleF1'],
            ['MiddleFinger2_L', 'L_MiddleF2'],
            ['MiddleFinger3_L', 'L_MiddleF3'],

            ['MiddleFinger1_L', 'L_MiddleF_HJ_01'],
            ['MiddleFinger2_L', 'L_MiddleF_HJ_02'],
            ['MiddleFinger3_L', 'L_MiddleF_HJ_03'],
            ['MiddleFinger1_L', 'L_MiddleF_HJ_00'],
            ['MiddleFinger1_L', 'L_MiddleF_HJ_04'],

            ['Left wrist', 'L_Palm'],

            ['RingFinger1_L', 'L_RingF1'],
            ['RingFinger2_L', 'L_RingF2'],
            ['RingFinger3_L', 'L_RingF3'],

            ['RingFinger1_L', 'L_RingF_HJ_01'],
            ['RingFinger2_L', 'L_RingF_HJ_02'],
            ['RingFinger3_L', 'L_RingF_HJ_03'],
            ['RingFinger1_L', 'L_RingF_HJ_00'],
            ['RingFinger1_L', 'L_RingF_HJ_04'],

            ['LittleFinger1_L', 'L_PinkyF1'],
            ['LittleFinger2_L', 'L_PinkyF2'],
            ['LittleFinger3_L', 'L_PinkyF3'],

            ['LittleFinger1_L', 'L_PinkyF_HJ_01'],
            ['LittleFinger2_L', 'L_PinkyF_HJ_02'],
            ['LittleFinger3_L', 'L_PinkyF_HJ_03'],
            ['LittleFinger1_L', 'L_PinkyF_HJ_00'],
            ['LittleFinger1_L', 'L_PinkyF_HJ_04'],

            ['Left wrist', 'L_HandRZ_HJ_00'],
            ['Left wrist', 'L_Hand_HJ_01'],
            ['Left wrist', 'L_Wep_Sub'],
            ['Left wrist', 'L_Hand_HJ_00'],

            ['zHandTwist_L', 'L_ForearmTwist_HJ_02'],
            ['Left elbow', 'L_ForearmRY_HJ_00'],
            ['Left elbow', 'L_ForearmRY_HJ_01'],
            ['zHandTwist_L', 'L_ForearmTwist_HJ_01'],
            ['Left elbow', 'L_ForearmTwist_HJ_00'],
            ['Left elbow', 'L_Forearm_HJ_00'],
            ['Left elbow', 'L_Elbow_HJ_00'],

            ['Left arm', 'L_UpperArmTwist_HJ_00'],

            ['zArmTwist_L', 'L_UpperArmTwist_HJ_01'],
            ['zArmTwist_L', 'L_Triceps_HJ_00'],
            ['zArmTwist_L', 'L_Biceps_HJ_00'],
            ['zArmTwist_L', 'L_Biceps_HJ_01'],
            ['zArmTwist_L', 'L_UpperArmTwist_HJ_02'],

            ['Left elbow', 'L_ForearmDouble_HJ_00'],
            ['Left arm', 'L_UpperArm_HJ_00'],
            ['Left arm', 'L_Deltoid_HJ_00'],
            ['Left arm', 'L_Deltoid_HJ_01'],
            ['Left arm', 'L_Deltoid_HJ_02'],
            ['Left arm', 'L_UpperArmDouble_HJ_00'],

            ['Left shoulder', 'L_Shoulder_HJ_00'],

            ['Right shoulder', 'R_Shoulder'],
            ['Right arm', 'R_UpperArm'],
            ['Right elbow', 'R_Forearm'],
            ['Right wrist', 'R_Hand'],
            ['Right wrist', 'R_Wep'],

            ['Thumb0_R', 'R_Thumb1'],
            ['Thumb1_R', 'R_Thumb2'],
            ['Thumb2_R', 'R_Thumb3'],

            ['Thumb0_R', 'R_Thumb_HJ_00'],
            ['Thumb1_R', 'R_Thumb_HJ_01'],
            ['Thumb2_R', 'R_Thumb_HJ_02'],
            ['Thumb0_R', 'R_Thumb_HJ_03'],

            ['IndexFinger1_R', 'R_IndexF1'],
            ['IndexFinger2_R', 'R_IndexF2'],
            ['IndexFinger3_R', 'R_IndexF3'],

            ['IndexFinger1_R', 'R_IndexF_HJ_01'],
            ['IndexFinger2_R', 'R_IndexF_HJ_02'],
            ['IndexFinger3_R', 'R_IndexF_HJ_03'],
            ['IndexFinger1_R', 'R_IndexF_HJ_00'],
            ['IndexFinger1_R', 'R_IndexF_HJ_04'],

            ['MiddleFinger1_R', 'R_MiddleF1'],
            ['MiddleFinger2_R', 'R_MiddleF2'],
            ['MiddleFinger3_R', 'R_MiddleF3'],

            ['MiddleFinger1_R', 'R_MiddleF_HJ_01'],
            ['MiddleFinger2_R', 'R_MiddleF_HJ_02'],
            ['MiddleFinger3_R', 'R_MiddleF_HJ_03'],
            ['MiddleFinger1_R', 'R_MiddleF_HJ_00'],
            ['MiddleFinger1_R', 'R_MiddleF_HJ_04'],

            ['Right wrist', 'R_Palm'],

            ['RingFinger1_R', 'R_RingF1'],
            ['RingFinger2_R', 'R_RingF2'],
            ['RingFinger3_R', 'R_RingF3'],

            ['RingFinger1_R', 'R_RingF_HJ_01'],
            ['RingFinger2_R', 'R_RingF_HJ_02'],
            ['RingFinger3_R', 'R_RingF_HJ_03'],
            ['RingFinger1_R', 'R_RingF_HJ_00'],
            ['RingFinger1_R', 'R_RingF_HJ_04'],

            ['LittleFinger1_R', 'R_PinkyF1'],
            ['LittleFinger2_R', 'R_PinkyF2'],
            ['LittleFinger3_R', 'R_PinkyF3'],

            ['LittleFinger1_R', 'R_PinkyF_HJ_01'],
            ['LittleFinger2_R', 'R_PinkyF_HJ_02'],
            ['LittleFinger3_R', 'R_PinkyF_HJ_03'],
            ['LittleFinger1_R', 'R_PinkyF_HJ_00'],
            ['LittleFinger1_R', 'R_PinkyF_HJ_04'],

            ['Right wrist', 'R_HandRZ_HJ_00'],
            ['Right wrist', 'R_Hand_HJ_01'],
            ['Right wrist', 'R_Wep_Sub'],
            ['Right wrist', 'R_Hand_HJ_00'],

            ['zHandTwist_R', 'R_ForearmTwist_HJ_02'],
            ['Right elbow', 'R_ForearmRY_HJ_00'],
            ['Right elbow', 'R_ForearmRY_HJ_01'],
            ['zHandTwist_R', 'R_ForearmTwist_HJ_01'],
            ['Right elbow', 'R_ForearmTwist_HJ_00'],
            ['Right elbow', 'R_Shield'],
            ['Right elbow', 'R_Forearm_HJ_00'],
            ['Right elbow', 'R_Elbow_HJ_00'],

            ['Right arm', 'R_UpperArmTwist_HJ_00'],

            ['zArmTwist_R', 'R_UpperArmTwist_HJ_01'],
            ['zArmTwist_R', 'R_Triceps_HJ_00'],
            ['zArmTwist_R', 'R_Biceps_HJ_00'],
            ['zArmTwist_R', 'R_Biceps_HJ_01'],
            ['zArmTwist_R', 'R_UpperArmTwist_HJ_02'],

            ['Right elbow', 'R_ForearmDouble_HJ_00'],
            ['Right arm', 'R_UpperArm_HJ_00'],
            ['Right arm', 'R_Deltoid_HJ_00'],
            ['Right arm', 'R_Deltoid_HJ_01'],
            ['Right arm', 'R_Deltoid_HJ_02'],
            ['Right arm', 'R_UpperArmDouble_HJ_00'],

            ['Right shoulder', 'R_Shoulder_HJ_00'],

            ['Left shoulder', 'L_Traps_HJ_00'],
            ['Left shoulder', 'L_Traps_HJ_01'],
            ['Left shoulder', 'L_Pec_HJ_00'],
            ['Left shoulder', 'L_Pec_HJ_01'],
            ['Left shoulder', 'L_Lats_HJ_00'],
            ['Left shoulder', 'L_Lats_HJ_01'],

            ['Right shoulder', 'R_Traps_HJ_00'],
            ['Right shoulder', 'R_Traps_HJ_01'],
            ['Right shoulder', 'R_Pec_HJ_00'],
            ['Right shoulder', 'R_Pec_HJ_01'],
            ['Right shoulder', 'R_Lats_HJ_00'],
            ['Right shoulder', 'R_Lats_HJ_01'],

            ['Chest', 'Spine_2_HJ_00'],

            #    ['','R_Bust_HJ_00'],
            #    ['','R_Bust_HJ_01'],
            #    ['','L_Bust_HJ_00'],
            #    ['','L_Bust_HJ_01'],

            ['Upper Chest', 'Spine_1_HJ_00'],
            ['Spine', 'Spine_0_HJ_00'],

            ['Left leg', 'L_Thigh'],
            ['Left knee', 'L_Knee'],
            ['Left knee', 'L_Shin'],
            ['Left ankle', 'L_Foot'],
            #    ['Left toe','L_Instep'],
            ['Left toe', 'L_Toe'],
            ['Left ankle', 'L_Foot_HJ_00'],
            ['Left knee', 'L_Calf_HJ_00'],
            ['Left knee', 'L_Shin_HJ_00'],
            ['Left knee', 'L_Shin_HJ_01'],
            ['Left knee', 'L_Knee_HJ_00'],
            ['Left knee', 'L_KneeDouble_HJ_00'],
            ['Left knee', 'L_KneeRX_HJ_00'],
            ['Left leg', 'L_ThighTwist_HJ_00'],
            ['Left leg', 'L_ThighTwist_HJ_01'],
            ['Left knee', 'L_ThighTwist_HJ_02'],

            ['Right leg', 'R_Thigh'],
            ['Right knee', 'R_Knee'],
            ['Right knee', 'R_Shin'],
            ['Right ankle', 'R_Foot'],
            #    ['Right toe','R_Instep'],
            ['Right toe', 'R_Toe'],
            ['Right ankle', 'R_Foot_HJ_00'],
            ['Right knee', 'R_Calf_HJ_00'],
            ['Right knee', 'R_Shin_HJ_00'],
            ['Right knee', 'R_Shin_HJ_01'],
            ['Right knee', 'R_Knee_HJ_00'],
            ['Right knee', 'R_KneeDouble_HJ_00'],
            ['Right knee', 'R_KneeRX_HJ_00'],
            ['Right leg', 'R_ThighTwist_HJ_00'],
            ['Right leg', 'R_ThighTwist_HJ_01'],
            ['Right knee', 'R_ThighTwist_HJ_02'],

            ['Left leg', 'L_ThighRZ_HJ_00'],
            ['Left leg', 'L_ThighRZ_HJ_01'],
            ['Right leg', 'R_ThighRZ_HJ_00'],
            ['Right leg', 'R_ThighRZ_HJ_01'],
            ['Left leg', 'L_Hip_HJ_00'],
            ['Left leg', 'L_Hip_HJ_01'],
            ['Right leg', 'R_Hip_HJ_00'],
            ['Right leg', 'R_Hip_HJ_01'],
            ['Left leg', 'L_ThighRX_HJ_00'],
            ['Left leg', 'L_ThighRX_HJ_01'],
            ['Right leg', 'R_ThighRX_HJ_00'],
            ['Right leg', 'R_ThighRX_HJ_01'],

            ['Hips', 'Hip_HJ_00'],
        ]
        
rename_vg_fixed_name_list = [
            ['Hips', 'Hip_HJ_00'],
            ['Spine', 'Spine_0_HJ_00'],
            ['Chest', 'Spine_1_HJ_00'],
            ['Upper Chest', 'Spine_2_HJ_00'],
            ['Neck', 'Neck_0_HJ_00'],
            ['Head', 'Head'],

            ['Left shoulder', 'L_Shoulder_HJ_00'],
            ['zArmTwist_L', 'L_UpperArmTwist_HJ_01'],
            ['Left elbow', 'L_ForearmTwist_HJ_00'],
            ['Left wrist', 'L_Hand'],
            ['Thumb0_L', 'L_Thumb1'],
            ['Thumb1_L', 'L_Thumb2'],
            ['Thumb2_L', 'L_Thumb3'],
            ['IndexFinger1_L', 'L_IndexF1'],
            ['IndexFinger2_L', 'L_IndexF2'],
            ['IndexFinger3_L', 'L_IndexF3'],
            ['MiddleFinger1_L', 'L_MiddleF1'],
            ['MiddleFinger2_L', 'L_MiddleF2'],
            ['MiddleFinger3_L', 'L_MiddleF3'],
            ['自定义L', 'L_Palm'],
            ['RingFinger1_L', 'L_RingF1'],
            ['RingFinger2_L', 'L_RingF2'],
            ['RingFinger3_L', 'L_RingF3'],
            ['LittleFinger1_L', 'L_PinkyF1'],
            ['LittleFinger2_L', 'L_PinkyF2'],
            ['LittleFinger3_L', 'L_PinkyF3'],

            ['Right shoulder', 'R_Shoulder_HJ_00'],
            ['zArmTwist_R', 'R_UpperArmTwist_HJ_01'],
            ['Right elbow', 'R_ForearmTwist_HJ_00'],
            ['Right wrist', 'R_Hand'],
            ['Thumb0_R', 'R_Thumb1'],
            ['Thumb1_R', 'R_Thumb2'],
            ['Thumb2_R', 'R_Thumb3'],
            ['IndexFinger1_R', 'R_IndexF1'],
            ['IndexFinger2_R', 'R_IndexF2'],
            ['IndexFinger3_R', 'R_IndexF3'],
            ['MiddleFinger1_R', 'R_MiddleF1'],
            ['MiddleFinger2_R', 'R_MiddleF2'],
            ['MiddleFinger3_R', 'R_MiddleF3'],
            ['自定义R', 'R_Palm'],
            ['RingFinger1_R', 'R_RingF1'],
            ['RingFinger2_R', 'R_RingF2'],
            ['RingFinger3_R', 'R_RingF3'],
            ['LittleFinger1_R', 'R_PinkyF1'],
            ['LittleFinger2_R', 'R_PinkyF2'],
            ['LittleFinger3_R', 'R_PinkyF3'],

            ['Left leg', 'L_Thigh'],
            ['Left knee', 'L_Shin'],
            ['Left ankle', 'L_Foot'],
            ['Left toe', 'L_Toe'],

            ['Right leg', 'R_Thigh'],
            ['Right knee', 'R_Shin'],
            ['Right ankle', 'R_Foot'],
            ['Right toe', 'R_Toe'],

            ['+ElbowAux_L', 'L_Elbow_HJ_00'],
            ['ElbowAux_L', 'L_Elbow_HJ_00'],
            ['Left arm', 'L_Deltoid_HJ_00'],
            ['zHandTwist_L', 'L_ForearmTwist_HJ_02'],

            ['+ElbowAux_R', 'R_Elbow_HJ_00'],
            ['ElbowAux_R', 'R_Elbow_HJ_00'],
            ['Right arm', 'R_Deltoid_HJ_00'],
            ['zHandTwist_R', 'R_ForearmTwist_HJ_02'],

            ['OhButt_L', 'L_Hip_HJ_01'],
            ['+KneeAux_L', 'L_Knee_HJ_00'],
            ['KneeAux_L', 'L_Knee_HJ_00'],

            ['OhButt_R', 'R_Hip_HJ_01'],
            ['+KneeAux_R', 'R_Knee_HJ_00'],
            ['KneeAux_R', 'R_Knee_HJ_00'],
        ]