# 编写字典时最好按照骨骼层级的顺序来编写，简单来说就是胯到胸到头，左臂到左手，右臂到右手，左腿到左脚，右腿到右脚。
# 注意，请确保rename_vg_fixed_name_list字典中的前6个骨骼名，普遍都存在于该字典对应的一类外部骨架中，插件会用于判定选择的字典是否匹配当前选中的外部骨架。

snap_bone_fixed_name_list = [
            ['bonefunction_013', 'Hip'],
            ['bonefunction_001', 'Spine_0'],
            ['bonefunction_002', 'Spine_1'],
            ['bonefunction_002', 'Spine_2'],
            ['bonefunction_003', 'Neck_0'],
            ['bonefunction_003', 'Neck_0_HJ_00'],

            ['bonefunction_004', 'Head'],

            ['bonefunction_005', 'L_Shoulder'],
            ['bonefunction_080', 'L_UpperArm'],
            ['bonefunction_007', 'L_Forearm'],
            ['bonefunction_008', 'L_Hand'],
            ['bonefunction_008', 'L_Wep'],

            ['bonefunction_031', 'L_Thumb1'],
            ['bonefunction_032', 'L_Thumb2'],
            ['bonefunction_033', 'L_Thumb3'],

            ['bonefunction_031', 'L_Thumb_HJ_00'],
            ['bonefunction_032', 'L_Thumb_HJ_01'],
            ['bonefunction_033', 'L_Thumb_HJ_02'],
            ['bonefunction_031', 'L_Thumb_HJ_03'],

            ['bonefunction_034', 'L_IndexF1'],
            ['bonefunction_035', 'L_IndexF2'],
            ['bonefunction_036', 'L_IndexF3'],

            ['bonefunction_034', 'L_IndexF_HJ_01'],
            ['bonefunction_035', 'L_IndexF_HJ_02'],
            ['bonefunction_036', 'L_IndexF_HJ_03'],
            ['bonefunction_034', 'L_IndexF_HJ_00'],
            ['bonefunction_034', 'L_IndexF_HJ_04'],

            ['bonefunction_037', 'L_MiddleF1'],
            ['bonefunction_038', 'L_MiddleF2'],
            ['bonefunction_039', 'L_MiddleF3'],

            ['bonefunction_037', 'L_MiddleF_HJ_01'],
            ['bonefunction_038', 'L_MiddleF_HJ_02'],
            ['bonefunction_039', 'L_MiddleF_HJ_03'],
            ['bonefunction_037', 'L_MiddleF_HJ_00'],
            ['bonefunction_037', 'L_MiddleF_HJ_04'],

            ['bonefunction_040', 'L_Palm'],

            ['bonefunction_041', 'L_RingF1'],
            ['bonefunction_042', 'L_RingF2'],
            ['bonefunction_043', 'L_RingF3'],

            ['bonefunction_041', 'L_RingF_HJ_01'],
            ['bonefunction_042', 'L_RingF_HJ_02'],
            ['bonefunction_043', 'L_RingF_HJ_03'],
            ['bonefunction_041', 'L_RingF_HJ_00'],
            ['bonefunction_041', 'L_RingF_HJ_04'],

            ['bonefunction_044', 'L_PinkyF1'],
            ['bonefunction_045', 'L_PinkyF2'],
            ['bonefunction_046', 'L_PinkyF3'],

            ['bonefunction_044', 'L_PinkyF_HJ_01'],
            ['bonefunction_045', 'L_PinkyF_HJ_02'],
            ['bonefunction_046', 'L_PinkyF_HJ_03'],
            ['bonefunction_044', 'L_PinkyF_HJ_00'],
            ['bonefunction_044', 'L_PinkyF_HJ_04'],

            ['bonefunction_008', 'L_HandRZ_HJ_00'],
            ['bonefunction_008', 'L_Hand_HJ_01'],
            ['bonefunction_008', 'L_Wep_Sub'],
            ['bonefunction_008', 'L_Hand_HJ_00'],

            ['bonefunction_081', 'L_ForearmTwist_HJ_02'],
            ['bonefunction_007', 'L_ForearmRY_HJ_00'],
            ['bonefunction_007', 'L_ForearmRY_HJ_01'],
            ['bonefunction_081', 'L_ForearmTwist_HJ_01'],
            ['bonefunction_007', 'L_ForearmTwist_HJ_00'],
            ['bonefunction_007', 'L_Forearm_HJ_00'],
            ['bonefunction_007', 'L_Elbow_HJ_00'],

            ['bonefunction_080', 'L_UpperArmTwist_HJ_00'],

            ['bonefunction_006', 'L_UpperArmTwist_HJ_01'],
            ['bonefunction_006', 'L_Triceps_HJ_00'],
            ['bonefunction_006', 'L_Biceps_HJ_00'],
            ['bonefunction_006', 'L_Biceps_HJ_01'],
            ['bonefunction_006', 'L_UpperArmTwist_HJ_02'],

            ['bonefunction_007', 'L_ForearmDouble_HJ_00'],
            ['bonefunction_080', 'L_UpperArm_HJ_00'],
            ['bonefunction_080', 'L_Deltoid_HJ_00'],
            ['bonefunction_080', 'L_Deltoid_HJ_01'],
            ['bonefunction_080', 'L_Deltoid_HJ_02'],
            ['bonefunction_080', 'L_UpperArmDouble_HJ_00'],

            ['bonefunction_005', 'L_Shoulder_HJ_00'],

            ['bonefunction_009', 'R_Shoulder'],
            ['bonefunction_082', 'R_UpperArm'],
            ['bonefunction_011', 'R_Forearm'],
            ['bonefunction_012', 'R_Hand'],
            ['bonefunction_012', 'R_Wep'],

            ['bonefunction_048', 'R_Thumb1'],
            ['bonefunction_049', 'R_Thumb2'],
            ['bonefunction_050', 'R_Thumb3'],

            ['bonefunction_048', 'R_Thumb_HJ_00'],
            ['bonefunction_049', 'R_Thumb_HJ_01'],
            ['bonefunction_050', 'R_Thumb_HJ_02'],
            ['bonefunction_048', 'R_Thumb_HJ_03'],

            ['bonefunction_051', 'R_IndexF1'],
            ['bonefunction_052', 'R_IndexF2'],
            ['bonefunction_053', 'R_IndexF3'],

            ['bonefunction_051', 'R_IndexF_HJ_01'],
            ['bonefunction_052', 'R_IndexF_HJ_02'],
            ['bonefunction_053', 'R_IndexF_HJ_03'],
            ['bonefunction_051', 'R_IndexF_HJ_00'],
            ['bonefunction_051', 'R_IndexF_HJ_04'],

            ['bonefunction_054', 'R_MiddleF1'],
            ['bonefunction_055', 'R_MiddleF2'],
            ['bonefunction_056', 'R_MiddleF3'],

            ['bonefunction_054', 'R_MiddleF_HJ_01'],
            ['bonefunction_055', 'R_MiddleF_HJ_02'],
            ['bonefunction_056', 'R_MiddleF_HJ_03'],
            ['bonefunction_054', 'R_MiddleF_HJ_00'],
            ['bonefunction_054', 'R_MiddleF_HJ_04'],

            ['bonefunction_057', 'R_Palm'],

            ['bonefunction_058', 'R_RingF1'],
            ['bonefunction_059', 'R_RingF2'],
            ['bonefunction_060', 'R_RingF3'],

            ['bonefunction_058', 'R_RingF_HJ_01'],
            ['bonefunction_059', 'R_RingF_HJ_02'],
            ['bonefunction_060', 'R_RingF_HJ_03'],
            ['bonefunction_058', 'R_RingF_HJ_00'],
            ['bonefunction_058', 'R_RingF_HJ_04'],

            ['bonefunction_061', 'R_PinkyF1'],
            ['bonefunction_062', 'R_PinkyF2'],
            ['bonefunction_063', 'R_PinkyF3'],

            ['bonefunction_061', 'R_PinkyF_HJ_01'],
            ['bonefunction_062', 'R_PinkyF_HJ_02'],
            ['bonefunction_063', 'R_PinkyF_HJ_03'],
            ['bonefunction_061', 'R_PinkyF_HJ_00'],
            ['bonefunction_061', 'R_PinkyF_HJ_04'],

            ['bonefunction_012', 'R_HandRZ_HJ_00'],
            ['bonefunction_012', 'R_Hand_HJ_01'],
            ['bonefunction_012', 'R_Wep_Sub'],
            ['bonefunction_012', 'R_Hand_HJ_00'],

            ['bonefunction_083', 'R_ForearmTwist_HJ_02'],
            ['bonefunction_011', 'R_ForearmRY_HJ_00'],
            ['bonefunction_011', 'R_ForearmRY_HJ_01'],
            ['bonefunction_083', 'R_ForearmTwist_HJ_01'],
            ['bonefunction_011', 'R_ForearmTwist_HJ_00'],
            ['bonefunction_011', 'R_Shield'],
            ['bonefunction_011', 'R_Forearm_HJ_00'],
            ['bonefunction_011', 'R_Elbow_HJ_00'],

            ['bonefunction_082', 'R_UpperArmTwist_HJ_00'],

            ['bonefunction_010', 'R_UpperArmTwist_HJ_01'],
            ['bonefunction_010', 'R_Triceps_HJ_00'],
            ['bonefunction_010', 'R_Biceps_HJ_00'],
            ['bonefunction_010', 'R_Biceps_HJ_01'],
            ['bonefunction_010', 'R_UpperArmTwist_HJ_02'],

            ['bonefunction_011', 'R_ForearmDouble_HJ_00'],
            ['bonefunction_082', 'R_UpperArm_HJ_00'],
            ['bonefunction_082', 'R_Deltoid_HJ_00'],
            ['bonefunction_082', 'R_Deltoid_HJ_01'],
            ['bonefunction_082', 'R_Deltoid_HJ_02'],
            ['bonefunction_082', 'R_UpperArmDouble_HJ_00'],

            ['bonefunction_009', 'R_Shoulder_HJ_00'],

            ['bonefunction_005', 'L_Traps_HJ_00'],
            ['bonefunction_005', 'L_Traps_HJ_01'],
            ['bonefunction_005', 'L_Pec_HJ_00'],
            ['bonefunction_005', 'L_Pec_HJ_01'],
            ['bonefunction_005', 'L_Lats_HJ_00'],
            ['bonefunction_005', 'L_Lats_HJ_01'],

            ['bonefunction_009', 'R_Traps_HJ_00'],
            ['bonefunction_009', 'R_Traps_HJ_01'],
            ['bonefunction_009', 'R_Pec_HJ_00'],
            ['bonefunction_009', 'R_Pec_HJ_01'],
            ['bonefunction_009', 'R_Lats_HJ_00'],
            ['bonefunction_009', 'R_Lats_HJ_01'],

            ['bonefunction_002', 'Spine_2_HJ_00'],

            #    ['','R_Bust_HJ_00'],
            #    ['','R_Bust_HJ_01'],
            #    ['','L_Bust_HJ_00'],
            #    ['','L_Bust_HJ_01'],

            ['bonefunction_002', 'Spine_1_HJ_00'],
            ['bonefunction_001', 'Spine_0_HJ_00'],

            ['bonefunction_014', 'L_Thigh'],
            ['bonefunction_015', 'L_Knee'],
            ['bonefunction_015', 'L_Shin'],
            ['bonefunction_016', 'L_Foot'],

            ['bonefunction_017', 'L_Toe'],
            ['bonefunction_016', 'L_Foot_HJ_00'],
            ['bonefunction_015', 'L_Calf_HJ_00'],
            ['bonefunction_015', 'L_Shin_HJ_00'],
            ['bonefunction_015', 'L_Shin_HJ_01'],
            ['bonefunction_015', 'L_Knee_HJ_00'],
            ['bonefunction_015', 'L_KneeDouble_HJ_00'],
            ['bonefunction_015', 'L_KneeRX_HJ_00'],
            ['bonefunction_014', 'L_ThighTwist_HJ_00'],
            ['bonefunction_014', 'L_ThighTwist_HJ_01'],
            ['bonefunction_015', 'L_ThighTwist_HJ_02'],

            ['bonefunction_018', 'R_Thigh'],
            ['bonefunction_019', 'R_Knee'],
            ['bonefunction_019', 'R_Shin'],
            ['bonefunction_020', 'R_Foot'],

            ['bonefunction_021', 'R_Toe'],
            ['bonefunction_020', 'R_Foot_HJ_00'],
            ['bonefunction_019', 'R_Calf_HJ_00'],
            ['bonefunction_019', 'R_Shin_HJ_00'],
            ['bonefunction_019', 'R_Shin_HJ_01'],
            ['bonefunction_019', 'R_Knee_HJ_00'],
            ['bonefunction_019', 'R_KneeDouble_HJ_00'],
            ['bonefunction_019', 'R_KneeRX_HJ_00'],
            ['bonefunction_018', 'R_ThighTwist_HJ_00'],
            ['bonefunction_018', 'R_ThighTwist_HJ_01'],
            ['bonefunction_019', 'R_ThighTwist_HJ_02'],

            ['bonefunction_014', 'L_ThighRZ_HJ_00'],
            ['bonefunction_014', 'L_ThighRZ_HJ_01'],
            ['bonefunction_018', 'R_ThighRZ_HJ_00'],
            ['bonefunction_018', 'R_ThighRZ_HJ_01'],
            ['bonefunction_014', 'L_Hip_HJ_00'],
            ['bonefunction_014', 'L_Hip_HJ_01'],
            ['bonefunction_018', 'R_Hip_HJ_00'],
            ['bonefunction_018', 'R_Hip_HJ_01'],
            ['bonefunction_014', 'L_ThighRX_HJ_00'],
            ['bonefunction_014', 'L_ThighRX_HJ_01'],
            ['bonefunction_018', 'R_ThighRX_HJ_00'],
            ['bonefunction_018', 'R_ThighRX_HJ_01'],

            ['bonefunction_013', 'Hip_HJ_00'],
        ]
        
rename_vg_fixed_name_list = [
            ['bonefunction_000', 'COG'],
            ['bonefunction_013', 'Hip_HJ_00'],
            ['bonefunction_001', 'Spine_0_HJ_00'],
            ['bonefunction_002', 'Spine_1_HJ_00'],
            ['bonefunction_003', 'Neck_0_HJ_00'],
            ['bonefunction_004', 'Head'],

            ['bonefunction_005', 'L_Shoulder_HJ_00'],
            ['bonefunction_006', 'L_UpperArmTwist_HJ_01'],
            ['bonefunction_007', 'L_ForearmTwist_HJ_00'],
            ['bonefunction_008', 'L_Hand'],
            ['bonefunction_031', 'L_Thumb1'],
            ['bonefunction_032', 'L_Thumb2'],
            ['bonefunction_033', 'L_Thumb3'],
            ['bonefunction_034', 'L_IndexF1'],
            ['bonefunction_035', 'L_IndexF2'],
            ['bonefunction_036', 'L_IndexF3'],
            ['bonefunction_037', 'L_MiddleF1'],
            ['bonefunction_038', 'L_MiddleF2'],
            ['bonefunction_039', 'L_MiddleF3'],
            ['bonefunction_040', 'L_Palm'],
            ['bonefunction_041', 'L_RingF1'],
            ['bonefunction_042', 'L_RingF2'],
            ['bonefunction_043', 'L_RingF3'],
            ['bonefunction_044', 'L_PinkyF1'],
            ['bonefunction_045', 'L_PinkyF2'],
            ['bonefunction_046', 'L_PinkyF3'],

            ['bonefunction_009', 'R_Shoulder_HJ_00'],
            ['bonefunction_010', 'R_UpperArmTwist_HJ_01'],
            ['bonefunction_011', 'R_ForearmTwist_HJ_00'],
            ['bonefunction_012', 'R_Hand'],
            ['bonefunction_048', 'R_Thumb1'],
            ['bonefunction_049', 'R_Thumb2'],
            ['bonefunction_050', 'R_Thumb3'],
            ['bonefunction_051', 'R_IndexF1'],
            ['bonefunction_052', 'R_IndexF2'],
            ['bonefunction_053', 'R_IndexF3'],
            ['bonefunction_054', 'R_MiddleF1'],
            ['bonefunction_055', 'R_MiddleF2'],
            ['bonefunction_056', 'R_MiddleF3'],
            ['bonefunction_057', 'R_Palm'],
            ['bonefunction_058', 'R_RingF1'],
            ['bonefunction_059', 'R_RingF2'],
            ['bonefunction_060', 'R_RingF3'],
            ['bonefunction_061', 'R_PinkyF1'],
            ['bonefunction_062', 'R_PinkyF2'],
            ['bonefunction_063', 'R_PinkyF3'],

            ['bonefunction_014', 'L_Thigh'],
            ['bonefunction_015', 'L_Shin'],
            ['bonefunction_016', 'L_Foot'],
            ['bonefunction_017', 'L_Toe'],

            ['bonefunction_018', 'R_Thigh'],
            ['bonefunction_019', 'R_Shin'],
            ['bonefunction_020', 'R_Foot'],
            ['bonefunction_021', 'R_Toe'],

            ['bonefunction_071', 'L_Elbow_HJ_00'],
            ['bonefunction_080', 'L_Deltoid_HJ_00'],
            ['bonefunction_081', 'L_ForearmTwist_HJ_02'],

            ['bonefunction_073', 'R_Elbow_HJ_00'],
            ['bonefunction_082', 'R_Deltoid_HJ_00'],
            ['bonefunction_083', 'R_ForearmTwist_HJ_02'],

            ['bonefunction_074', 'L_Hip_HJ_01'],
            ['bonefunction_075', 'L_Knee_HJ_00'],

            ['bonefunction_076', 'R_Hip_HJ_01'],
            ['bonefunction_077', 'R_Knee_HJ_00'],

            ['bonefunction_070', 'L_Traps_HJ_01'],
            ['bonefunction_072', 'R_Traps_HJ_01'],
        ]