snap_bone_fixed_name_list = [
            ['Waist_00', 'Hip'],
            ['Spine_00', 'Spine_0'],
            ['Spine_01', 'Spine_1'],
            ['Spine_01', 'Spine_2'],
            ['Neck_00', 'Neck_0'],
            ['Neck_00', 'Neck_0_HJ_00'],

            ['Head_00', 'Head'],

            ['L_Arm_00', 'L_Shoulder'],
            ['L_Arm_01_T', 'L_UpperArm'],
            ['L_Arm_02', 'L_Forearm'],
            ['L_Arm_03', 'L_Hand'],
            ['L_Arm_03', 'L_Wep'],

            ['L_Finger_00', 'L_Thumb1'],
            ['L_Finger_01', 'L_Thumb2'],
            ['L_Finger_02', 'L_Thumb3'],

            ['L_Finger_00', 'L_Thumb_HJ_00'],
            ['L_Finger_01', 'L_Thumb_HJ_01'],
            ['L_Finger_02', 'L_Thumb_HJ_02'],
            ['L_Finger_00', 'L_Thumb_HJ_03'],

            ['L_Finger_03', 'L_IndexF1'],
            ['L_Finger_04', 'L_IndexF2'],
            ['L_Finger_05', 'L_IndexF3'],

            ['L_Finger_03', 'L_IndexF_HJ_01'],
            ['L_Finger_04', 'L_IndexF_HJ_02'],
            ['L_Finger_05', 'L_IndexF_HJ_03'],
            ['L_Finger_03', 'L_IndexF_HJ_00'],
            ['L_Finger_03', 'L_IndexF_HJ_04'],

            ['L_Finger_06', 'L_MiddleF1'],
            ['L_Finger_07', 'L_MiddleF2'],
            ['L_Finger_08', 'L_MiddleF3'],

            ['L_Finger_06', 'L_MiddleF_HJ_01'],
            ['L_Finger_07', 'L_MiddleF_HJ_02'],
            ['L_Finger_08', 'L_MiddleF_HJ_03'],
            ['L_Finger_06', 'L_MiddleF_HJ_00'],
            ['L_Finger_06', 'L_MiddleF_HJ_04'],

            ['L_Finger_09', 'L_Palm'],

            ['L_Finger_10', 'L_RingF1'],
            ['L_Finger_11', 'L_RingF2'],
            ['L_Finger_12', 'L_RingF3'],

            ['L_Finger_10', 'L_RingF_HJ_01'],
            ['L_Finger_11', 'L_RingF_HJ_02'],
            ['L_Finger_12', 'L_RingF_HJ_03'],
            ['L_Finger_10', 'L_RingF_HJ_00'],
            ['L_Finger_10', 'L_RingF_HJ_04'],

            ['L_Finger_13', 'L_PinkyF1'],
            ['L_Finger_14', 'L_PinkyF2'],
            ['L_Finger_15', 'L_PinkyF3'],

            ['L_Finger_13', 'L_PinkyF_HJ_01'],
            ['L_Finger_14', 'L_PinkyF_HJ_02'],
            ['L_Finger_15', 'L_PinkyF_HJ_03'],
            ['L_Finger_13', 'L_PinkyF_HJ_00'],
            ['L_Finger_13', 'L_PinkyF_HJ_04'],

            ['L_Arm_03', 'L_HandRZ_HJ_00'],
            ['L_Arm_03', 'L_Hand_HJ_01'],
            ['L_Arm_03', 'L_Wep_Sub'],
            ['L_Arm_03', 'L_Hand_HJ_00'],

            ['L_Arm_02_T', 'L_ForearmTwist_HJ_02'],
            ['L_Arm_02', 'L_ForearmRY_HJ_00'],
            ['L_Arm_02', 'L_ForearmRY_HJ_01'],
            ['L_Arm_02_T', 'L_ForearmTwist_HJ_01'],
            ['L_Arm_02', 'L_ForearmTwist_HJ_00'],
            ['L_Arm_02', 'L_Forearm_HJ_00'],
            ['L_Arm_02', 'L_Elbow_HJ_00'],

            ['L_Arm_01_T', 'L_UpperArmTwist_HJ_00'],

            ['L_Arm_01', 'L_UpperArmTwist_HJ_01'],
            ['L_Arm_01', 'L_Triceps_HJ_00'],
            ['L_Arm_01', 'L_Biceps_HJ_00'],
            ['L_Arm_01', 'L_Biceps_HJ_01'],
            ['L_Arm_01', 'L_UpperArmTwist_HJ_02'],

            ['L_Arm_02', 'L_ForearmDouble_HJ_00'],
            ['L_Arm_01_T', 'L_UpperArm_HJ_00'],
            ['L_Arm_01_T', 'L_Deltoid_HJ_00'],
            ['L_Arm_01_T', 'L_Deltoid_HJ_01'],
            ['L_Arm_01_T', 'L_Deltoid_HJ_02'],
            ['L_Arm_01_T', 'L_UpperArmDouble_HJ_00'],

            ['L_Arm_00', 'L_Shoulder_HJ_00'],

            ['R_Arm_00', 'R_Shoulder'],
            ['R_Arm_01_T', 'R_UpperArm'],
            ['R_Arm_02', 'R_Forearm'],
            ['R_Arm_03', 'R_Hand'],
            ['R_Arm_03', 'R_Wep'],

            ['R_Finger_00', 'R_Thumb1'],
            ['R_Finger_01', 'R_Thumb2'],
            ['R_Finger_02', 'R_Thumb3'],

            ['R_Finger_00', 'R_Thumb_HJ_00'],
            ['R_Finger_01', 'R_Thumb_HJ_01'],
            ['R_Finger_02', 'R_Thumb_HJ_02'],
            ['R_Finger_00', 'R_Thumb_HJ_03'],

            ['R_Finger_03', 'R_IndexF1'],
            ['R_Finger_04', 'R_IndexF2'],
            ['R_Finger_05', 'R_IndexF3'],

            ['R_Finger_03', 'R_IndexF_HJ_01'],
            ['R_Finger_04', 'R_IndexF_HJ_02'],
            ['R_Finger_05', 'R_IndexF_HJ_03'],
            ['R_Finger_03', 'R_IndexF_HJ_00'],
            ['R_Finger_03', 'R_IndexF_HJ_04'],

            ['R_Finger_06', 'R_MiddleF1'],
            ['R_Finger_07', 'R_MiddleF2'],
            ['R_Finger_08', 'R_MiddleF3'],

            ['R_Finger_06', 'R_MiddleF_HJ_01'],
            ['R_Finger_07', 'R_MiddleF_HJ_02'],
            ['R_Finger_08', 'R_MiddleF_HJ_03'],
            ['R_Finger_06', 'R_MiddleF_HJ_00'],
            ['R_Finger_06', 'R_MiddleF_HJ_04'],

            ['R_Grip_00', 'R_Palm'],

            ['R_Finger_09', 'R_RingF1'],
            ['R_Finger_10', 'R_RingF2'],
            ['R_Finger_11', 'R_RingF3'],

            ['R_Finger_09', 'R_RingF_HJ_01'],
            ['R_Finger_10', 'R_RingF_HJ_02'],
            ['R_Finger_11', 'R_RingF_HJ_03'],
            ['R_Finger_09', 'R_RingF_HJ_00'],
            ['R_Finger_09', 'R_RingF_HJ_04'],

            ['R_Finger_12', 'R_PinkyF1'],
            ['R_Finger_13', 'R_PinkyF2'],
            ['R_Finger_14', 'R_PinkyF3'],

            ['R_Finger_12', 'R_PinkyF_HJ_01'],
            ['R_Finger_13', 'R_PinkyF_HJ_02'],
            ['R_Finger_14', 'R_PinkyF_HJ_03'],
            ['R_Finger_12', 'R_PinkyF_HJ_00'],
            ['R_Finger_12', 'R_PinkyF_HJ_04'],

            ['R_Arm_03', 'R_HandRZ_HJ_00'],
            ['R_Arm_03', 'R_Hand_HJ_01'],
            ['R_Arm_03', 'R_Wep_Sub'],
            ['R_Arm_03', 'R_Hand_HJ_00'],

            ['R_Arm_02_T', 'R_ForearmTwist_HJ_02'],
            ['R_Arm_02', 'R_ForearmRY_HJ_00'],
            ['R_Arm_02', 'R_ForearmRY_HJ_01'],
            ['R_Arm_02_T', 'R_ForearmTwist_HJ_01'],
            ['R_Arm_02', 'R_ForearmTwist_HJ_00'],
            ['R_Arm_02', 'R_Shield'],
            ['R_Arm_02', 'R_Forearm_HJ_00'],
            ['R_Arm_02', 'R_Elbow_HJ_00'],

            ['R_Arm_01_T', 'R_UpperArmTwist_HJ_00'],

            ['R_Arm_01', 'R_UpperArmTwist_HJ_01'],
            ['R_Arm_01', 'R_Triceps_HJ_00'],
            ['R_Arm_01', 'R_Biceps_HJ_00'],
            ['R_Arm_01', 'R_Biceps_HJ_01'],
            ['R_Arm_01', 'R_UpperArmTwist_HJ_02'],

            ['R_Arm_02', 'R_ForearmDouble_HJ_00'],
            ['R_Arm_01_T', 'R_UpperArm_HJ_00'],
            ['R_Arm_01_T', 'R_Deltoid_HJ_00'],
            ['R_Arm_01_T', 'R_Deltoid_HJ_01'],
            ['R_Arm_01_T', 'R_Deltoid_HJ_02'],
            ['R_Arm_01_T', 'R_UpperArmDouble_HJ_00'],

            ['R_Arm_00', 'R_Shoulder_HJ_00'],

            ['L_Arm_00', 'L_Traps_HJ_00'],
            ['L_Arm_00', 'L_Traps_HJ_01'],
            ['L_Arm_00', 'L_Pec_HJ_00'],
            ['L_Arm_00', 'L_Pec_HJ_01'],
            ['L_Arm_00', 'L_Lats_HJ_00'],
            ['L_Arm_00', 'L_Lats_HJ_01'],

            ['R_Arm_00', 'R_Traps_HJ_00'],
            ['R_Arm_00', 'R_Traps_HJ_01'],
            ['R_Arm_00', 'R_Pec_HJ_00'],
            ['R_Arm_00', 'R_Pec_HJ_01'],
            ['R_Arm_00', 'R_Lats_HJ_00'],
            ['R_Arm_00', 'R_Lats_HJ_01'],

            ['Spine_01', 'Spine_2_HJ_00'],

            #    ['','R_Bust_HJ_00'],
            #    ['','R_Bust_HJ_01'],
            #    ['','L_Bust_HJ_00'],
            #    ['','L_Bust_HJ_01'],

            ['Spine_01', 'Spine_1_HJ_00'],
            ['Spine_00', 'Spine_0_HJ_00'],

            ['L_Leg_00', 'L_Thigh'],
            ['L_Leg_01', 'L_Knee'],
            ['L_Leg_01', 'L_Shin'],
            ['L_Leg_02', 'L_Foot'],

            ['L_Leg_03', 'L_Toe'],
            ['L_Leg_02', 'L_Foot_HJ_00'],
            ['L_Leg_01', 'L_Calf_HJ_00'],
            ['L_Leg_01', 'L_Shin_HJ_00'],
            ['L_Leg_01', 'L_Shin_HJ_01'],
            ['L_Leg_01', 'L_Knee_HJ_00'],
            ['L_Leg_01', 'L_KneeDouble_HJ_00'],
            ['L_Leg_01', 'L_KneeRX_HJ_00'],
            ['L_Leg_00', 'L_ThighTwist_HJ_00'],
            ['L_Leg_00', 'L_ThighTwist_HJ_01'],
            ['L_Leg_01', 'L_ThighTwist_HJ_02'],

            ['R_Leg_00', 'R_Thigh'],
            ['R_Leg_01', 'R_Knee'],
            ['R_Leg_01', 'R_Shin'],
            ['R_Leg_02', 'R_Foot'],

            ['R_Leg_03', 'R_Toe'],
            ['R_Leg_02', 'R_Foot_HJ_00'],
            ['R_Leg_01', 'R_Calf_HJ_00'],
            ['R_Leg_01', 'R_Shin_HJ_00'],
            ['R_Leg_01', 'R_Shin_HJ_01'],
            ['R_Leg_01', 'R_Knee_HJ_00'],
            ['R_Leg_01', 'R_KneeDouble_HJ_00'],
            ['R_Leg_01', 'R_KneeRX_HJ_00'],
            ['R_Leg_00', 'R_ThighTwist_HJ_00'],
            ['R_Leg_00', 'R_ThighTwist_HJ_01'],
            ['R_Leg_01', 'R_ThighTwist_HJ_02'],

            ['L_Leg_00', 'L_ThighRZ_HJ_00'],
            ['L_Leg_00', 'L_ThighRZ_HJ_01'],
            ['R_Leg_00', 'R_ThighRZ_HJ_00'],
            ['R_Leg_00', 'R_ThighRZ_HJ_01'],
            ['L_Leg_00', 'L_Hip_HJ_00'],
            ['L_Leg_00', 'L_Hip_HJ_01'],
            ['R_Leg_00', 'R_Hip_HJ_00'],
            ['R_Leg_00', 'R_Hip_HJ_01'],
            ['L_Leg_00', 'L_ThighRX_HJ_00'],
            ['L_Leg_00', 'L_ThighRX_HJ_01'],
            ['R_Leg_00', 'R_ThighRX_HJ_00'],
            ['R_Leg_00', 'R_ThighRX_HJ_01'],

            ['Waist_00', 'Hip_HJ_00'],
        ]
        
rename_vg_fixed_name_list = [
            ['Waist_00', 'Hip_HJ_00'],
            ['Spine_00', 'Spine_0_HJ_00'],
            ['Spine_01', 'Spine_1_HJ_00'],
            ['Neck_00', 'Neck_0_HJ_00'],
            ['Head_00', 'Head'],

            ['L_Arm_00', 'L_Shoulder_HJ_00'],
            ['L_Arm_01', 'L_UpperArmTwist_HJ_01'],
            ['L_Arm_02', 'L_ForearmTwist_HJ_00'],
            ['L_Arm_03', 'L_Hand'],
            ['L_Finger_00', 'L_Thumb1'],
            ['L_Finger_01', 'L_Thumb2'],
            ['L_Finger_02', 'L_Thumb3'],
            ['L_Finger_03', 'L_IndexF1'],
            ['L_Finger_04', 'L_IndexF2'],
            ['L_Finger_05', 'L_IndexF3'],
            ['L_Finger_06', 'L_MiddleF1'],
            ['L_Finger_07', 'L_MiddleF2'],
            ['L_Finger_08', 'L_MiddleF3'],
            ['L_Finger_09', 'L_Palm'],
            ['L_Finger_10', 'L_RingF1'],
            ['L_Finger_11', 'L_RingF2'],
            ['L_Finger_12', 'L_RingF3'],
            ['L_Finger_13', 'L_PinkyF1'],
            ['L_Finger_14', 'L_PinkyF2'],
            ['L_Finger_15', 'L_PinkyF3'],

            ['R_Arm_00', 'R_Shoulder_HJ_00'],
            ['R_Arm_01', 'R_UpperArmTwist_HJ_01'],
            ['R_Arm_02', 'R_ForearmTwist_HJ_00'],
            ['R_Arm_03', 'R_Hand'],
            ['R_Finger_00', 'R_Thumb1'],
            ['R_Finger_01', 'R_Thumb2'],
            ['R_Finger_02', 'R_Thumb3'],
            ['R_Finger_03', 'R_IndexF1'],
            ['R_Finger_04', 'R_IndexF2'],
            ['R_Finger_05', 'R_IndexF3'],
            ['R_Finger_06', 'R_MiddleF1'],
            ['R_Finger_07', 'R_MiddleF2'],
            ['R_Finger_08', 'R_MiddleF3'],
            ['R_Grip_00', 'R_Palm'],
            ['R_Finger_09', 'R_RingF1'],
            ['R_Finger_10', 'R_RingF2'],
            ['R_Finger_11', 'R_RingF3'],
            ['R_Finger_12', 'R_PinkyF1'],
            ['R_Finger_13', 'R_PinkyF2'],
            ['R_Finger_14', 'R_PinkyF3'],

            ['L_Leg_00', 'L_Thigh'],
            ['L_Leg_01', 'L_Shin'],
            ['L_Leg_02', 'L_Foot'],
            ['L_Leg_03', 'L_Toe'],

            ['R_Leg_00', 'R_Thigh'],
            ['R_Leg_01', 'R_Shin'],
            ['R_Leg_02', 'R_Foot'],
            ['R_Leg_03', 'R_Toe'],

            ['L_Arm_01_W', 'L_Elbow_HJ_00'],
            ['L_Arm_01_T', 'L_Deltoid_HJ_00'],
            ['L_Arm_02_T', 'L_ForearmTwist_HJ_02'],

            ['R_Arm_01_W', 'R_Elbow_HJ_00'],
            ['R_Arm_01_T', 'R_Deltoid_HJ_00'],
            ['R_Arm_02_T', 'R_ForearmTwist_HJ_02'],

            ['L_Leg_00_W', 'L_Hip_HJ_01'],
            ['L_Leg_01_W', 'L_Knee_HJ_00'],

            ['R_Leg_00_W', 'R_Hip_HJ_01'],
            ['R_Leg_01_W', 'R_Knee_HJ_00'],

            ['L_Arm_00_W', 'L_Traps_HJ_01'],
            ['R_Arm_00_W', 'R_Traps_HJ_01'],
        ]